### PR TITLE
Add more libs to composer.json

### PR DESCRIPTION
**Pull request by clemens-tolboom**
It is a waste of time to find missing dependencies. Especially for people following the README.

This PR solves the cryptic

> Note: this library uses namespaces so please remember to add the relevant use clauses.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I suspect it's good to improve the readme. However specifying these libraries here fixes their version here and gives you a possibly incomplete list with possibly not needed items. The one here so far is certainly incomplete if you want to work with Wikidata.

**Comment by addshore** [comment]
This relates to something that I have had sat in my inbox for a while which I have not yet created.
addwiki should have a wikidata-api specific lib.
This would essentially contain a factory & stuff to help using the library with wikidata

I have filed https://phabricator.wikimedia.org/T157637 regarding this.
as a result I probably won't merge this PR!

**Comment by clemens-tolboom** [comment]
Fair enough not take in this PR. :)

**Comment by addshore** [comment]
I'm going to close this PR, but this will be tackled in https://github.com/addwiki/addwiki/issues/15

**Pull request closed without merging**
